{ makeNixosModules, importHomeModules, importNixosModules, ... }: makeNixosModules {

  homeModules = importHomeModules [
    "git.nix"
    "nixvim"
    "shell.nix"
  ];

  nixosModules = importNixosModules [
    "ssh.nix"
    "networking.nix"
    "locale.nix"
    "docker.nix"
  ];

  config = _: {
    programs.dconf.enable = true;

    # Configure console keymap
    console.keyMap = "uk";

    # Define a user account. Don't forget to set a password with ‘passwd’.
    users.users.porygon = {
      isNormalUser = true;
      description = "-- All Powerful Data Manager --";
      extraGroups = [ "networkmanager" "wheel" ];
    };

    # This value determines the NixOS release from which the default
    # settings for stateful data, like file locations and database versions
    # on your system were taken. It‘s perfectly fine and recommended to leave
    # this value at the release version of the first install of this system.
    # Before changing this value read the documentation for this option
    # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
    system.stateVersion = "24.05"; # Did you read the comment?
  };

  hardware = { config, lib, modulesPath, ... }: {
    # Do not modify this attribute set!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    imports =
      [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot = {
      initrd = {
        availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
        kernelModules = [ ];
      };
      kernelModules = [ "kvm-amd" ];
      extraModulePackages = [ ];
      loader = {
        systemd-boot.enable = true;
        efi.canTouchEfiVariables = true;
      };
    };

    fileSystems."/" =
      {
        device = "/dev/disk/by-uuid/7625509c-6cfa-4dc7-90e4-904190c9664a";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      {
        device = "/dev/disk/by-uuid/62CF-D4CC";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices = [ ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp24s0.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
