{ stylix, makeModules, importHomeModules, importNixosModules, ... }: makeModules {



  homeModules = importHomeModules [
    "fonts.nix"
    "firefox.nix"
    "git.nix"
    "window-manager"
    "nixvim"
    "startup.nix"
    "shell.nix"
    "terminal.nix"
    "screen.nix"
    "qutebrowser"
    "packages.nix"
    "stylix.nix"
    "wofi.nix"
    "social_media.nix"
    "swaylock.nix"
    "tyranitar_keyboard.nix"
  ] ++ [
    stylix.homeModules.stylix
    {
      wayland.windowManager.sway.extraConfig = ''
        input * {
          xkb_layout "gb"
        }
      '';
    }
  ];
  nixosModules = importNixosModules [
    "lockscreen.nix"
    "display-manager.nix"
    "bootloader.nix"
    "ssh.nix"
    "audio.nix"
    "networking.nix"
    "locale.nix"
    "screensharing.nix"
    "docker.nix"
  ];

  config = { pkgs, ... }: {
    # Bootloader - move to hardware.
    boot.loader.systemd-boot.enable = true;
    boot.loader.efi.canTouchEfiVariables = true;

    programs.dconf.enable = true;

    environment.systemPackages = with pkgs; [
      android-studio
      hmcl
      ardour
      autotalent
      qpwgraph
    ];

    hardware.graphics = {
      enable = true;
      enable32Bit = true;
    };

    # Configure console keymap
    console.keyMap = "uk";

    # Enable CUPS to print documents.
    services.printing.enable = true;

    # Enable touchpad support (enabled default in most desktopManager).
    # services.xserver.libinput.enable = true;

    # Define a user account. Don't forget to set a password with ‘passwd’.
    users.users.hallayus = {
      isNormalUser = true;
      description = "Hallayus";
      extraGroups = [ "networkmanager" "wheel" ];
    };

    # This value determines the NixOS release from which the default
    # settings for stateful data, like file locations and database versions
    # on your system were taken. It‘s perfectly fine and recommended to leave
    # this value at the release version of the first install of this system.
    # Before changing this value read the documentation for this option
    # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
    system.stateVersion = "24.05"; # Did you read the comment?

  };

  hardware = { config, lib, modulesPath, ... }: {
    # Do not modify this attribute set!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    imports =
      [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      {
        device = "/dev/disk/by-uuid/7625509c-6cfa-4dc7-90e4-904190c9664a";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      {
        device = "/dev/disk/by-uuid/62CF-D4CC";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices = [ ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp24s0.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
