{ stylix, makeClanMachine, importHomeModules, importNixosModules, ... }: makeClanMachine {

  users.oscar = {
    home.stateVersion = "21.11";
    imports = importHomeModules [
      "fonts.nix"
      "firefox.nix"
      "git.nix"
      "sway"
      "nixvim"
      "shell.nix"
      "terminal.nix"
      "screen.nix"
      "qutebrowser"
      "packages.nix"
      "stylix.nix"
      "wofi.nix"
      "social_media.nix"
      "devices.nix"
      "llm.nix"
      "litellm.nix"
    ] ++ [
      stylix.homeModules.stylix
      {
        wayland.windowManager.sway.extraConfig = ''
          input * {
            xkb_layout "gb"
          }
        '';
      }
      {
        modules.eww = {
          networkInterface = "wlo1";
        };
      }
      {
        wayland.windowManager.sway.config.output = {
          "DP-2" = {
            position = "0 0";
          };
          "DP-1" = {
            position = "320 1440";
          };
        };
      }
    ];
  };

  nixosModules = importNixosModules [
    "greetd.nix"
    "bootloader.nix"
    "ssh.nix"
    "audio.nix"
    "networking.nix"
    "locale.nix"
    "screensharing.nix"
    "docker.nix"
    "clan.nix"
    "devices.nix"
    "ollama.nix"
  ];

  config = { pkgs, ... }: {
    programs.sway = {
      enable = true;
      wrapperFeatures.gtk = true;
    };

    programs.dconf.enable = true;

    environment.systemPackages = with pkgs; [
      android-studio
      hmcl
      ardour
      autotalent
      qpwgraph
    ];


    security.polkit.enable = true;

    # Configure console keymap
    console.keyMap = "uk";

    services = {
      # Enable CUPS to print documents.
      printing.enable = true;
      xserver.videoDrivers = [ "nvidia" ];

      ollama = {
        acceleration = "cuda";
      };
    };

    # Enable touchpad support (enabled default in most desktopManager).
    # services.xserver.libinput.enable = true;

    users.users.oscar = {
      isNormalUser = true;
      description = "Oscar";
      extraGroups = [ "networkmanager" "wheel" ];
      hashedPassword = "$6$.PzdYbCD9pl6UWLW$cEEKjuxoesTh8bj9GyVkcFtlp8Ng742bnjSZsrWkpa1HUZpxw/r9u1MmN5EOjbjMkxjWil00mx/w1Y7gCNLbI/";
    };

    users.mutableUsers = true;

    # This value determines the NixOS release from which the default
    # settings for stateful data, like file locations and database versions
    # on your system were taken. It‘s perfectly fine and recommended to leave
    # this value at the release version of the first install of this system.
    # Before changing this value read the documentation for this option
    # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
    system.stateVersion = "24.05"; # Did you read the comment?

  };

  hardware = { config, lib, modulesPath, ... }: {
    # Do not modify this attribute set!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    imports =
      [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

    boot = {
      initrd = {
        availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
        kernelModules = [
          "amdgpu"
          "nvidia"
          "nvidia_modeset"
          "nvidia_uvm"
          "nvidia_drm"
        ];
      };

      kernelModules = [ "kvm-amd" ];
      extraModulePackages = [ ];
      loader = {
        systemd-boot.enable = true;
        efi.canTouchEfiVariables = true;
      };
      kernelParams = [
        "quiet"
        "loglevel=3"
        "rd.systemd.show_status=false"
        "udev.log_level=3"
        "nvidia-drm.modeset=1"
      ];
    };

    hardware.graphics = {
      enable = true;
      enable32Bit = true;
    };

    hardware.nvidia = {
      modesetting.enable = true;
      open = true;
      nvidiaSettings = true;
      package = config.boot.kernelPackages.nvidiaPackages.stable;
    };

    fileSystems."/" =
      {
        device = "/dev/disk/by-uuid/7625509c-6cfa-4dc7-90e4-904190c9664a";
        fsType = "ext4";
      };

    fileSystems."/boot" =
      {
        device = "/dev/disk/by-uuid/0DE8-A9A0";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    swapDevices = [ ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp24s0.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
